export { default as CtaSection1 } from "./1/page"
export { default as CtaSection2 } from "./2/page"
export { default as CtaSection3 } from "./3/page"
export { default as CtaSection4 } from "./4/page"
export { default as CtaSection5 } from "./5/page"
export { default as CtaSection6 } from "./6/page"