export { default as Footer1 } from "./1/page"
export { default as Footer2 } from "./2/page"
export { default as Footer3 } from "./3/page"
export { default as Footer4 } from "./4/page"
export { default as Footer5 } from "./5/page"
export { default as Footer6 } from "./6/page"