export { Navbar as Navbar1 } from "./1/page"
export { Navbar as Navbar2 } from "./2/page"
export { Navbar as Navbar3 } from "./3/page"
export { Navbar as Navbar4 } from "./4/page"
export { Navbar as Navbar5 } from "./5/page"
export { Navbar as Navbar6 } from "./6/page"
export { Navbar as Navbar7 } from "./7/page"