export { default as Metrics1 } from "./1/page"
export { default as Metrics2 } from "./2/page"
export { default as Metrics3 } from "./3/page"
export { default as Metrics4 } from "./4/page"
export { default as Metrics5 } from "./5/page"
export { default as Metrics6 } from "./6/page"
export { default as Metrics7 } from "./7/page"